INSERT INTO book_category (category_name)
VALUES
('Fiction'),
('Non-Fiction'),
('Science Fiction'),
('Fantasy'),
('Mystery'),
('Thriller'),
('Romance'),
('Horror'),
('Biography'),
('Autobiography'),
('Historical'),
('Young Adult'),
('Children'),
('Self-Help'),
('Health & Wellness'),
('Science'),
('Technology'),
('Travel'),
('Cooking'),
('Art'),
('Poetry'),
('Religion'),
('Philosophy'),
('Education'),
('Business'),
('Economics'),
('Politics'),
('Sports'),
('Comics'),
('Graphic Novels');
