INSERT INTO reviews (customer_id, book_id, review_text, rating)
VALUES
(1, 1, 'Buku yang sangat menarik dan informatif. Saya sangat menikmatinya.', 5),
(2, 2, 'Tulisan yang bagus, tapi alurnya sedikit lambat.', 4),
(3, 3, 'Sangat menginspirasi dan penuh dengan wawasan baru.', 5),
(4, 4, 'Ceritanya cukup menarik, tetapi karakternya kurang berkembang.', 3),
(5, 5, 'Tidak sesuai dengan ekspektasi saya, agak membosankan.', 2),
(6, 6, 'Buku ini sangat membantu dalam penelitian saya.', 5),
(7, 7, 'Banyak informasi yang bermanfaat, tetapi penyampaiannya kurang menarik.', 4),
(8, 8, 'Plot twist yang mengejutkan di akhir cerita!', 5),
(9, 9, 'Alur cerita yang bagus, tetapi bahasanya terlalu sulit dipahami.', 3),
(10, 10, 'Sangat inspiratif dan memberikan banyak pelajaran hidup.', 5),
(11, 11, 'Cukup menghibur, tetapi ada beberapa bagian yang membingungkan.', 3),
(12, 12, 'Penulisannya sangat indah, seperti puisi.', 4),
(13, 13, 'Buku ini memberikan perspektif baru yang menarik.', 5),
(14, 14, 'Saya menemukan beberapa kesalahan fakta dalam buku ini.', 2),
(15, 15, 'Ceritanya sangat menyentuh hati.', 5),
(16, 16, 'Buku ini sedikit membosankan di tengah-tengahnya.', 3),
(17, 17, 'Penjelasan yang sangat jelas dan mudah dipahami.', 4),
(18, 18, 'Sangat mengecewakan, saya tidak menikmati buku ini.', 1),
(19, 19, 'Buku yang sangat lengkap dan detail.', 5),
(20, 20, 'Ceritanya bagus, tetapi penulisannya kurang baik.', 3),
(1, 5, 'Saya sangat menyukai karakter utamanya.', 4),
(2, 6, 'Buku ini sangat berkesan bagi saya.', 5),
(3, 7, 'Banyak bagian yang bertele-tele dan tidak penting.', 2),
(4, 8, 'Penulis sangat berbakat, buku yang luar biasa!', 5),
(5, 9, 'Cukup bagus, tapi tidak ada yang istimewa.', 3),
(6, 10, 'Informasi yang sangat berguna dan akurat.', 5),
(7, 11, 'Tidak sesuai dengan judulnya.', 2),
(8, 12, 'Saya sangat terinspirasi oleh buku ini.', 5),
(9, 13, 'Alur cerita yang terlalu lambat.', 2),
(10, 14, 'Penulisannya sangat detail dan mendalam.', 4),
(11, 15, 'Buku ini membuat saya berpikir ulang tentang banyak hal.', 5),
(12, 16, 'Banyak kesalahan ketik dalam buku ini.', 1),
(13, 17, 'Plot yang menarik dan tidak terduga.', 4),
(14, 18, 'Saya tidak bisa menyelesaikan buku ini, terlalu membosankan.', 1),
(15, 19, 'Sangat informatif dan mudah dipahami.', 5),
(16, 20, 'Buku ini sangat menghibur dan menarik.', 4),
(17, 1, 'Saya sangat menikmati setiap halaman dari buku ini.', 5),
(18, 2, 'Ceritanya agak klise dan mudah ditebak.', 3);
